# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**



In [1]:
#Vector represented as one dimentional array
# Just a single row or column of elements
#structure : Line

#matrix has 2 dimensions: rows and columns
#grid with multiple rows and columns
#structure: Grid

**2. How to import `NumPy` library?** 

In [2]:
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

In [3]:
list_1 = [1,2,3,4,5]

In [4]:
# To avoid overwriting the output, please code here 

import numpy as np
list_1=[1,2,3,4,5]
arr1=np.array(list_1)
print((arr1, f"numpy.{type(arr1).__name__}"))

(array([1, 2, 3, 4, 5]), 'numpy.ndarray')


**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [5]:
# To avoid overwriting the output, please code here 
import numpy as np
array=np.arange(0,6)
print(f"array({array.tolist()})")

array([0, 1, 2, 3, 4, 5])


**5. Generate an `array of "5" zeros` **

In [6]:
# To avoid overwriting the output, please code here 
import numpy as np
array=np.zeros(5)
print(f"array({np.array2string(array,separator = ', ')})")

array([0., 0., 0., 0., 0.])


**6. Generate the following `matrix`.**

In [7]:
# To avoid overwriting the output, please code here 
import numpy as np
array=np.zeros((3,4))
print(f"array({np.array2string(array,separator = ', ', prefix='array(')})")

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])


**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [8]:
# To avoid overwriting the output, please code here 
import numpy as np
arr=np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


**8. Generate an array of "5" tens.**

In [9]:
# To avoid overwriting the output, please code here 
array=np.ones(5)*10
print(f"array({np.array2string(array, separator=', ')})")

array([10., 10., 10., 10., 10.])


**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [10]:
# To avoid overwriting the output, please code here 
array=np.arange(52,100,2)
print(f"array({np.array2string(array, separator=',')})")

array([52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,90,92,94,96,98])


**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [11]:
# To avoid overwriting the output, please code here 
import numpy as np
array=np.linspace(0,1,10)
step = float(array[1] - array[0])
print((array, step))


(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]), 0.1111111111111111)


**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [12]:
# Generating vector array
array=np.arange(25)
print(f"array({array.tolist()})")


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])


In [13]:
# reshape to convert into 2-d
matrix = array.reshape(5, 5)

print(f"array({np.array2string(matrix, separator=', ',prefix='array(')})")

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])


In [14]:
# Using shape
import numpy as np

array = np.arange(25)
array.shape = (5, 5)

print(f"array({np.array2string(array, separator=', ', prefix='array(')})")

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])


**12. Please generate the following matrix.**

In [15]:
# To avoid overwriting the output, please code here 
array=np.arange(0.1,2.6,0.1).reshape(5,5)
print(f"array({np.array2string(array,separator=', ',prefix='array(')})")


array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])


**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [16]:
# To avoid overwriting the output, please code here 
import numpy as np
array=np.linspace(0,24,25, dtype=int).reshape(5,5)
print("array(" + np.array2string(array, separator=', ', prefix='array(') + ")")

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])


**14. What is the main difference between `linspace()` and `arange()`?**

In [17]:
license():
    1. structure: np.linspace(start,stop,number)
    2. Return the array containing the specified number of elements in a given range
    
arange():
    1. structure: np.linspace(start,stop,step)
    2. Return an array in  the given range increment by the step size.
    

SyntaxError: invalid syntax (3091151778.py, line 1)

**15. How to generate a single random integer number using NumPy built-in function?**

In [ ]:
# To avoid overwriting the output, please code here 
array=np.random.randint(0,10)
print(array)

7


**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [ ]:
# To avoid overwriting the output, please code here 
import numpy as np

array = np.random.rand(7, 5)
print(array)

[[0.21548943 0.58816032 0.63876283 0.66648935 0.04976606]
 [0.71181558 0.6067373  0.8992807  0.38285009 0.10607015]
 [0.37013486 0.23285832 0.41503042 0.3069726  0.78320115]
 [0.38010936 0.46631179 0.15200047 0.6843953  0.33898227]
 [0.15364183 0.60816565 0.33150188 0.73498825 0.98586392]
 [0.99243239 0.30649908 0.72632847 0.42565028 0.14887424]
 [0.15436988 0.94506948 0.88429193 0.18067929 0.23575286]]


[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
, [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
, [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
, [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
, [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
, [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
, [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [ ]:
# To avoid overwriting the output, please code here 
matrix=np.identity(5)*5
print(f"array({np.array2string(matrix, separator=', ',prefix='array(')})")


array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])


array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 